### ISSUE TITLE
Lose a service

### ISSUE THREAD

**Issue by VinkDong** [jaegertracing/spark-dependencies#27] opened 2018-01-24 03:02 UTC
I just tested message tracing via [Kafka](https://github.com/opentracing-contrib/java-kafka-client), I can get tracing as follow:
![image](https://user-images.githubusercontent.com/10599904/35312178-32829706-00f5-11e8-87cc-e3af655400b9.png)

but there is no service `kafka-consumer` in dependencies :

![image](https://user-images.githubusercontent.com/10599904/35312209-5ca92d4c-00f5-11e8-8d95-300d151117ed.png)

**Comment by pavolloffay** [comment] 2018-01-24 08:35
@VinkDong did you run the job for the period of time when service `kafka-consumer` was called? 

What storage are you using? If elasticsearch could you please query data from ES and paste it here?

**Comment by VinkDong** [comment] 2018-01-24 09:00
@pavolloffay Thank you for the reply, I had run the job by docker for many times, Elasticsearch Data:

- jaeger-service-2018-01-24:
[jaeger-service-2018-01-24.log](https://github.com/jaegertracing/spark-dependencies/files/1659177/jaeger-service-2018-01-24.log)

- jaeger-span-2018-01-24:
[jaeger-span-2018-01-24.log](https://github.com/jaegertracing/spark-dependencies/files/1659183/jaeger-span-2018-01-24.log)

**Comment by pavolloffay** [comment] 2018-01-24 10:36
all spans with service name `kafka-cunsumer` have  "parentSpanID" : "0",` which means they are not linked to any parent.

Could you please paste json of the trace which is on the first picture. In the UI click on view options and trace json.

**Comment by VinkDong** [comment] 2018-01-24 15:29
Yes, I notice that Kafka message header just contains `uber-trace-id` I think I need to add something else manually.

the trace json : 
[16d7ee95211f63c0.txt](https://github.com/jaegertracing/spark-dependencies/files/1660344/16d7ee95211f63c0.txt)

**Comment by pavolloffay** [comment] 2018-01-24 16:03
Span with service name `kafka-cunsumer` has more processes. I am not sure how it is possible cc @yurishkuro 

```json
"processes":{  
            "p1":{  
               "serviceName":"spring-demo",
               "tags":[  
                  {  
                     "key":"hostname",
                     "type":"string",
                     "value":"DongVinkdeMacBook-Pro.local"
                  },
                  {  
                     "key":"ip",
                     "type":"string",
                     "value":"10.211.99.23"
                  },
                  {  
                     "key":"jaeger.version",
                     "type":"string",
                     "value":"Java-0.22.0-RC3"
                  }
               ]
            },
            "p2":{  
               "serviceName":"spring-boot",
               "tags":[  
                  {  
                     "key":"hostname",
                     "type":"string",
                     "value":"DongVinkdeMacBook-Pro.local"
                  },
                  {  
                     "key":"ip",
                     "type":"string",
                     "value":"10.211.99.23"
                  },
                  {  
                     "key":"jaeger.version",
                     "type":"string",
                     "value":"Java-0.22.0-RC3"
                  }
               ]
            },
            "p3":{  
               "serviceName":"kafka-consumer",
               "tags":[  
                  {  
                     "key":"hostname",
                     "type":"string",
                     "value":"DongVinkdeMacBook-Pro.local"
                  },
                  {  
                     "key":"ip",
                     "type":"string",
                     "value":"10.211.99.23"
                  },
                  {  
                     "key":"jaeger.version",
                     "type":"string",
                     "value":"Java-0.22.0-RC3"
                  }
               ]
            }
         },
```

**Comment by pavolloffay** [comment] 2018-01-24 16:15
The issue is related to https://github.com/jaegertracing/spark-dependencies/issues/8. `kafka-consumer`'s parent span is stored in references array and not directly in `parentId` field. 

Once the referenced issue is implemented it will work. I will close this for now.

**Closed** 2018-01-24 16:15 UTC
